### ISSUE TITLE
重新npm i 后，就报错

### ISSUE THREAD

**Issue by ereddate** [dcloudio/uni-preset-vue#61]
npm i
npm run dev:mp-weixin

 ERROR  Error: Cannot find module 'cache-loader'
Require stack:
- D:\work\code\jstots\uni-ts\node_modules\@dcloudio\vue-cli-plugin-uni\lib\configure-webpack.js
- D:\work\code\jstots\uni-ts\node_modules\@dcloudio\vue-cli-plugin-uni\index.js
- D:\work\code\jstots\uni-ts\node_modules\@vue\cli-service\lib\Service.js
- D:\work\code\jstots\uni-ts\node_modules\@vue\cli-service\bin\vue-cli-service.js
Error: Cannot find module 'cache-loader'
Require stack:
- D:\work\code\jstots\uni-ts\node_modules\@dcloudio\vue-cli-plugin-uni\lib\configure-webpack.js
- D:\work\code\jstots\uni-ts\node_modules\@dcloudio\vue-cli-plugin-uni\index.js
- D:\work\code\jstots\uni-ts\node_modules\@vue\cli-service\lib\Service.js
- D:\work\code\jstots\uni-ts\node_modules\@vue\cli-service\bin\vue-cli-service.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename (D:\work\code\jstots\uni-ts\node_modules\module-alias\index.js:49:29)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at D:\work\code\jstots\uni-ts\node_modules\@dcloudio\vue-cli-plugin-uni\lib\configure-webpack.js:367:45
    at Array.forEach (<anonymous>)
    at D:\work\code\jstots\uni-ts\node_modules\@dcloudio\vue-cli-plugin-uni\lib\configure-webpack.js:365:33
    at Array.forEach (<anonymous>)
    at D:\work\code\jstots\uni-ts\node_modules\@dcloudio\vue-cli-plugin-uni\lib\configure-webpack.js:361:13
    at D:\work\code\jstots\uni-ts\node_modules\@vue\cli-service\lib\Service.js:251:21
    at Array.forEach (<anonymous>)
    at Service.resolveWebpackConfig (D:\work\code\jstots\uni-ts\node_modules\@vue\cli-service\lib\Service.js:248:30)
    at PluginAPI.resolveWebpackConfig (D:\work\code\jstots\uni-ts\node_modules\@vue\cli-service\lib\PluginAPI.js:132:25)
    at module.exports (D:\work\code\jstots\uni-ts\node_modules\@vue\cli-service\lib\commands\build\resolveAppConfig.js:46:14)
    at getWebpackConfig (D:\work\code\jstots\uni-ts\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:88:88)
    at getWebpackConfigs (D:\work\code\jstots\uni-ts\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:121:13)
    at build (D:\work\code\jstots\uni-ts\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:160:26)
    at D:\work\code\jstots\uni-ts\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:79:11
    at Service.run (D:\work\code\jstots\uni-ts\node_modules\@vue\cli-service\lib\Service.js:230:12)
    at Object.<anonymous> (D:\work\code\jstots\uni-ts\node_modules\@vue\cli-service\bin\vue-cli-service.js:36:9)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

**Comment by ereddate** [comment]
删除node_mod后试了几次还是不行

**Comment by zhetengbiji** [comment]
执行 ```npm run info``` 打印一下信息

**Comment by ereddate** [comment]
使用原有package-lock.json就没有问题

**Comment by zhetengbiji** [comment]
执行 npm run info 打印一下信息
