### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by seekcx** [dcloudio/uni-preset-vue#66]
HbuilderX 直接运行 vite-ts 分支，报错：

```
14:22:09.531 /xxx/node_modules/vite/dist/node-cjs/publicUtils.cjs:64
14:22:09.531     const cache = options.cache ?? new SplitVendorChunkCache();
14:22:09.538                                  ^
14:22:09.539 SyntaxError: Unexpected token '?'
14:22:09.544     at wrapSafe (internal/modules/cjs/loader.js:915:16)
14:22:09.560     at Module._compile (internal/modules/cjs/loader.js:963:27)
14:22:09.577     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
14:22:09.578     at Module.load (internal/modules/cjs/loader.js:863:32)
14:22:09.593     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
14:22:09.610     at Module.require (internal/modules/cjs/loader.js:887:19)
14:22:09.627     at require (internal/modules/cjs/helpers.js:74:18)
14:22:09.628     at Object.<anonymous> (/Users/abel/Desktop/labs/uni-preset-vue/node_modules/vite/index.cjs:7:31)
14:22:09.644     at Module._compile (internal/modules/cjs/loader.js:999:30)
14:22:09.660     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by zhetengbiji** [comment]
内置 node 版本过低，更新到 HBuilderX alpha

**Comment by seekcx** [comment]
非常感谢
