### ISSUE TITLE
Hello uni-app 在支付宝小程序上跑不起来，报错

### ISSUE THREAD

**Issue by chzhuo** [dcloudio/uni-preset-vue#70]
![image](https://user-images.githubusercontent.com/10919124/208039370-24af27be-6c15-4c8b-b3e4-bf6558b61379.png)
安装后 package.json
```json
{
  "name": "my-project3",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "npm run dev:h5",
    "build": "npm run build:h5",
    "build:app-plus": "cross-env NODE_ENV=production UNI_PLATFORM=app-plus vue-cli-service uni-build",
    "build:custom": "cross-env NODE_ENV=production uniapp-cli custom",
    "build:h5": "cross-env NODE_ENV=production UNI_PLATFORM=h5 vue-cli-service uni-build",
    "build:mp-360": "cross-env NODE_ENV=production UNI_PLATFORM=mp-360 vue-cli-service uni-build",
    "build:mp-alipay": "cross-env NODE_ENV=production UNI_PLATFORM=mp-alipay vue-cli-service uni-build",
    "build:mp-baidu": "cross-env NODE_ENV=production UNI_PLATFORM=mp-baidu vue-cli-service uni-build",
    "build:mp-jd": "cross-env NODE_ENV=production UNI_PLATFORM=mp-jd vue-cli-service uni-build",
    "build:mp-kuaishou": "cross-env NODE_ENV=production UNI_PLATFORM=mp-kuaishou vue-cli-service uni-build",
    "build:mp-lark": "cross-env NODE_ENV=production UNI_PLATFORM=mp-lark vue-cli-service uni-build",
    "build:mp-qq": "cross-env NODE_ENV=production UNI_PLATFORM=mp-qq vue-cli-service uni-build",
    "build:mp-toutiao": "cross-env NODE_ENV=production UNI_PLATFORM=mp-toutiao vue-cli-service uni-build",
    "build:mp-weixin": "cross-env NODE_ENV=production UNI_PLATFORM=mp-weixin vue-cli-service uni-build",
    "build:mp-xhs": "cross-env NODE_ENV=production UNI_PLATFORM=mp-xhs vue-cli-service uni-build",
    "build:quickapp-native": "cross-env NODE_ENV=production UNI_PLATFORM=quickapp-native vue-cli-service uni-build",
    "build:quickapp-webview": "cross-env NODE_ENV=production UNI_PLATFORM=quickapp-webview vue-cli-service uni-build",
    "build:quickapp-webview-huawei": "cross-env NODE_ENV=production UNI_PLATFORM=quickapp-webview-huawei vue-cli-service uni-build",
    "build:quickapp-webview-union": "cross-env NODE_ENV=production UNI_PLATFORM=quickapp-webview-union vue-cli-service uni-build",
    "dev:app-plus": "cross-env NODE_ENV=development UNI_PLATFORM=app-plus vue-cli-service uni-build --watch",
    "dev:custom": "cross-env NODE_ENV=development uniapp-cli custom",
    "dev:h5": "cross-env NODE_ENV=development UNI_PLATFORM=h5 vue-cli-service uni-serve",
    "dev:mp-360": "cross-env NODE_ENV=development UNI_PLATFORM=mp-360 vue-cli-service uni-build --watch",
    "dev:mp-alipay": "cross-env NODE_ENV=development UNI_PLATFORM=mp-alipay vue-cli-service uni-build --watch",
    "dev:mp-baidu": "cross-env NODE_ENV=development UNI_PLATFORM=mp-baidu vue-cli-service uni-build --watch",
    "dev:mp-jd": "cross-env NODE_ENV=development UNI_PLATFORM=mp-jd vue-cli-service uni-build --watch",
    "dev:mp-kuaishou": "cross-env NODE_ENV=development UNI_PLATFORM=mp-kuaishou vue-cli-service uni-build --watch",
    "dev:mp-lark": "cross-env NODE_ENV=development UNI_PLATFORM=mp-lark vue-cli-service uni-build --watch",
    "dev:mp-qq": "cross-env NODE_ENV=development UNI_PLATFORM=mp-qq vue-cli-service uni-build --watch",
    "dev:mp-toutiao": "cross-env NODE_ENV=development UNI_PLATFORM=mp-toutiao vue-cli-service uni-build --watch",
    "dev:mp-weixin": "cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch",
    "dev:mp-xhs": "cross-env NODE_ENV=development UNI_PLATFORM=mp-xhs vue-cli-service uni-build --watch",
    "dev:quickapp-native": "cross-env NODE_ENV=development UNI_PLATFORM=quickapp-native vue-cli-service uni-build --watch",
    "dev:quickapp-webview": "cross-env NODE_ENV=development UNI_PLATFORM=quickapp-webview vue-cli-service uni-build --watch",
    "dev:quickapp-webview-huawei": "cross-env NODE_ENV=development UNI_PLATFORM=quickapp-webview-huawei vue-cli-service uni-build --watch",
    "dev:quickapp-webview-union": "cross-env NODE_ENV=development UNI_PLATFORM=quickapp-webview-union vue-cli-service uni-build --watch",
    "info": "node node_modules/@dcloudio/vue-cli-plugin-uni/commands/info.js",
    "serve:quickapp-native": "node node_modules/@dcloudio/uni-quickapp-native/bin/serve.js",
    "test:android": "cross-env UNI_PLATFORM=app-plus UNI_OS_NAME=android jest -i",
    "test:h5": "cross-env UNI_PLATFORM=h5 jest -i",
    "test:ios": "cross-env UNI_PLATFORM=app-plus UNI_OS_NAME=ios jest -i",
    "test:mp-baidu": "cross-env UNI_PLATFORM=mp-baidu jest -i",
    "test:mp-weixin": "cross-env UNI_PLATFORM=mp-weixin jest -i"
  },
  "dependencies": {
    "@dcloudio/uni-app": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-app-plus": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-h5": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-i18n": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-360": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-alipay": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-baidu": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-jd": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-kuaishou": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-lark": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-qq": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-toutiao": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-vue": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-weixin": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-mp-xhs": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-quickapp-native": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-quickapp-webview": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-stacktracey": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-stat": "^2.0.1-alpha-36920221121001",
    "@vue/shared": "^3.0.0",
    "core-js": "^3.6.5",
    "flyio": "^0.6.2",
    "vue": "^2.6.11",
    "vuex": "^3.2.0"
  },
  "devDependencies": {
    "@dcloudio/types": "^3.0.4",
    "@dcloudio/uni-automator": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-cli-i18n": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-cli-shared": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-helper-json": "*",
    "@dcloudio/uni-migration": "^2.0.1-alpha-36920221121001",
    "@dcloudio/uni-template-compiler": "^2.0.1-alpha-36920221121001",
    "@dcloudio/vue-cli-plugin-hbuilderx": "^2.0.1-alpha-36920221121001",
    "@dcloudio/vue-cli-plugin-uni": "^2.0.1-alpha-36920221121001",
    "@dcloudio/vue-cli-plugin-uni-optimize": "^2.0.1-alpha-36920221121001",
    "@dcloudio/webpack-uni-mp-loader": "^2.0.1-alpha-36920221121001",
    "@dcloudio/webpack-uni-pages-loader": "^2.0.1-alpha-36920221121001",
    "@vue/cli-plugin-babel": "~4.5.15",
    "@vue/cli-service": "~4.5.15",
    "babel-plugin-import": "^1.11.0",
    "cross-env": "^7.0.2",
    "jest": "^25.4.0",
    "mini-types": "*",
    "miniprogram-api-typings": "*",
    "postcss-comment": "^2.0.0",
    "sass": "^1.49.8",
    "sass-loader": "^8.0.2",
    "vue-template-compiler": "^2.6.11"
  },
  "browserslist": [
    "Android >= 4.4",
    "ios >= 9"
  ],
  "uni-app": {
    "scripts": {}
  }
}

```

小程序开发者工具版本：版本3.2.6 (3.2.6)
![image](https://user-images.githubusercontent.com/10919124/208040081-f381922a-0ff9-4a2e-9ee7-fa4250a6382d.png)

报错信息，刚开始打开不报错只是一直加载中，我点击了刷新，然后报错如下：
```bash
[APPX][Page] pages/tabBar/component/component/2 CallMethod error Cannot read properties of undefined (reading '__call_hook')/TypeError: Cannot read properties of undefined (reading '__call_hook')
    at Object.onUnload (http://127.0.0.1:58792/index.worker.js?hash=bb681c69&from_service_worker=true&url=file%3A%2F%2F%2Findex.html&page=pages%2FtabBar%2Fcomponent%2Fcomponent&chInfo=ch_scan&referrerInfo=%7B%7D&ap_framework_sceneId=1011&enablePolyfillWorker=true&ap_framework_sceneId=1011:9604:22)
    at e.invokePublicMethod (https://appx/af-appx.worker.min.js:6:135338)
    at e.invokeLifeCycle (https://appx/af-appx.worker.min.js:6:134827)
    at e.performLifeHook (https://appx/af-appx.worker.min.js:6:146375)
    at b (https://appx/af-appx.worker.min.js:6:5493)
    at e.r.<computed> [as performLifeHook] (https://appx/af-appx.worker.min.js:6:44136)
    at e.setStateFromState (https://appx/af-appx.worker.min.js:6:148078)
    at e.setState (https://appx/af-appx.worker.min.js:6:146098)
    at e.onPageUnload (https://appx/af-appx.worker.min.js:6:145966)
    at e.onPageUnload (https://appx/af-appx.worker.min.js:6:245599) 1671173368557

```

**Comment by zhetengbiji** [comment]
参考一下：https://ask.dcloud.net.cn/question/159840

是不是类似问题
